CXX ?= g++ CFLAGS = -Wall -Wconversion -O3 -fPIC SHVER = 2 OS = $(shell uname)



c



all: svm-train svm-predict svm-scale

lib: svm.o
	if [ "$(OS)" = "Darwin" ]; then \
		SHARED_LIB_FLAG="-dynamiclib -W1,-install_name,libsvm.so.$(SHVER)"; \
	else \
		SHARED_LIB_FLAG="-shared "; \
	fi; \
	$(CXX) $${SHARED_LIB_FLAG} svm.o ./libOpenCL.so gpuImplementations/OpenCLLibsvmVersionMultiKernel/OpenCLGeneral.o gpuImplementations/OpenCLLibsvmVersionMultiKernel/OpenCLKernel.o -lm -L/opt/AMDAPP/lib/x86_64/ -I/opt/AMDAPP/include -I~/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ -o libsvm.so.$(SHVER)

svm-predict: svm-predict.c svm.o OpenCLKernel.o
	$(CXX) $(CFLAGS) svm-predict.c  -o svm-predict svm.o gpuImplementations/OpenCLLibsvmVersionMultiKernel/OpenCLGeneral.o gpuImplementations/OpenCLLibsvmVersionMultiKernel/OpenCLKernel.o -lm -L/opt/AMDAPP/lib/x86_64/ -I/opt/AMDAPP/include -I~/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ ./libOpenCL.so

svm-train: svm-train.c svm.o OpenCLKernel.o
	$(CXX) $(CFLAGS) svm-train.c -o svm-train svm.o gpuImplementations/OpenCLLibsvmVersionMultiKernel/OpenCLGeneral.o gpuImplementations/OpenCLLibsvmVersionMultiKernel/OpenCLKernel.o -lm -L/opt/AMDAPP/lib/x86_64/ -I/opt/AMDAPP/include -I~/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc/ ./libOpenCL.so 

svm-scale: svm-scale.c
	$(CXX) $(CFLAGS) svm-scale.c -o svm-scale

svm.o: svm.cpp
	$(CXX) $(CFLAGS) -I/opt/AMDAPP/include -I/veu/jcordero/NVIDIA_GPU_Computing_SDK/OpenCL/common/inc -c svm.cpp 

OpenCLKernel.o:
	make -C gpuImplementations/OpenCLLibsvmVersionMultiKernel/

clean:
	rm -f *~ svm.o svm-train svm-predict svm-scale libsvm.so.$(SHVER)
	make -C gpuImplementations/OpenCLLibsvmVersionMultiKernel/ clean
